Repository UBC-MDS/DSCI-532_2025_3_QuantaTrack, pull requests merged in 2025-02, with the labels that each got.

#2 Repo structure
  CONTRIBUTING.md
  LICENSE
  README.md
  TEAM_CONTRACT.md
  reports/m1_proposal.md
  src/app.py
Labels: documentation

#7 Develop the Motivation and Purpose section of proposal
  README.md
  reports/m1_proposal.md
Labels: documentation

#9 Sketch
  img/sketch.png
  reports/m1_proposal.md
Labels: documentation

#6 Realtime price data update
  Makefile
  assets/style.css
  environment.yml
  src/__init__.py
  src/app.py
  src/callbacks.py
  src/layout.py
  src/qqqm_data.py
  src/xueqiu_data.py
Labels: enhancement

#15 Include data output from data webscrap code
  data/raw/NASDAQ100_2025-02-15T20-29.csv
Labels: enhancement

#16 Fixed LICENSE and Revised README
  CONTRIBUTING.md
  LICENSE.md
  Makefile
  README.md
Labels: documentation

#17 Revised Proposal Motivation and Purpose
  reports/m1_proposal.md
Labels: documentation

#31 App design: Table, PE chart, Search Box, industry filter, and file download
  src/callbacks.py
  src/layout.py
Labels: enhancement

#33 m2_reflection
  reports/m2_reflection.md
Labels: documentation

#35 M2 reflection
  reports/m2_reflection.md
Labels: documentation

#42 App design
  assets/style.css
  src/app.py
  src/callbacks.py
  src/layout.py
  src/plotting.py
Labels: documentation, enhancement

#44 App design: Formatting Consistency Fix
  src/layout.py
  src/plotting.py
Labels: enhancement

#46 M2 reflection updates
  reports/m2_reflection.md
Labels: documentation
